services:
  # Backend API Service
  - type: web
    name: project-management-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  # MongoDB Atlas (if using managed MongoDB)
  # Remove this section if using MongoDB Atlas
  - name: mongodb
    plan: free
